In [6]:
import numpy as np
import pandas as pd
from scipy.linalg import null_space, svd

In [7]:
coords = pd.read_csv('coords.csv')[['X','Y','Z','x', 'y']]
coords = coords.head(6).values
coords

array([[   0,    0,    0,  860,  833],
       [   0,    0,    1,  592,  712],
       [   1,    0,    0, 1157,  765],
       [   0,    1,    0,  844, 1196],
       [   0,    1,    1,  581, 1060],
       [   1,    1,    0, 1137, 1128]], dtype=int64)

In [8]:
a=[]
for i in range(coords.shape[0]): # para cada ponto e correspondente 3D
  x,y,z,u,v = coords[i,:]
  a.append([x,y,z,1,0,0,0,0,-u*x,-u*y,-u*z,-u])
  a.append([0,0,0,0,x,y,z,1,-v*x,-v*y,-v*z,-v])

In [9]:
a=np.array(a)
U, s, Vh = svd(a)
nm = Vh[-1,:]
nm /= nm [-1]
nm = nm.reshape((3,4))

In [12]:
M = nm
M

array([[ 3.00591922e+02, -2.80010999e+00, -2.38696328e+02,
         8.59856664e+02],
       [-6.57554125e+01,  3.81311094e+02, -8.60098875e+01,
         8.32993864e+02],
       [ 2.92108371e-03,  1.52999880e-02,  4.91315245e-02,
         1.00000000e+00]])

In [13]:
result = np.vstack([M, [0, 0, 0,1]])

In [14]:
result.reshape(-1)

array([ 3.00591922e+02, -2.80010999e+00, -2.38696328e+02,  8.59856664e+02,
       -6.57554125e+01,  3.81311094e+02, -8.60098875e+01,  8.32993864e+02,
        2.92108371e-03,  1.52999880e-02,  4.91315245e-02,  1.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00])

In [ ]:
np.array([
      [
        0.676717630859556,
        -0.7260889299729478,
        0.12185283687534432,
        -1.7413690456865782
      ],
      [
        0.2016652661093843,
        0.34198087240239494,
        0.9178127278241068,
        0.9275570864952053
      ],
      [
        -0.7080850009206952,
        -0.5965265699712264,
        0.37785140305350545,
        -10
      ],
      [
        0,
        0,
        0,
        1
      ]
    ]
    ).T.reshape(-1)

In [ ]:
M@np.array([[2, 1, 1, 1]]).T

In [15]:
q1 = M[0, :3].T
q2 = M[1, :3].T
q3 = M[2, :3].T
q4 = M[:3, 3]

In [16]:
Ox = (q1.T @ q3)
Oy = (q2.T @ q3)
Ox, Oy

(-10.892301949107086, 1.4161811983538963)

In [17]:
fx = ((q1.T@q1) - Ox**2)** (1/2)
fy = ((q2.T@q2) - Oy**2) ** (1/2)

fx, fy

(383.6934180797739, 396.3806498391522)

In [18]:
cm = np.zeros((3,4))

In [19]:
cm[2, :] = M[2, :]
cm[0, 0] = (Ox * M[2,0] - M[0,0]) / fx
cm[0, 1] = (Ox * M[2,1] - M[0,1]) / fx
cm[0, 2] = (Ox * M[2,2] - M[0,2]) / fx
cm[1, 0] = (Oy * M[2,0] - M[1,0]) / fy
cm[1, 1] = (Oy * M[2,1] - M[1,1]) / fy
cm[1, 2] = (Oy * M[2,2] - M[1,2]) / fy

cm[0, 3] = (Ox * M[2,3] - M[0,3]) / fx
cm[1, 3] = (Oy * M[2,3] - M[1,3]) / fy


In [22]:
cam_matrix = np.vstack([-cm, np.array([0, 0, 0, 1])])
np.array(cam_matrix).reshape(-1)

array([ 0.78349986, -0.00686344, -0.62070695,  2.26938729, -0.1659    ,
        0.96192745, -0.21716364,  2.09792704, -0.00292108, -0.01529999,
       -0.04913152, -1.        ,  0.        ,  0.        ,  0.        ,
        1.        ])